# Generated by Django 2.0.2 on 2018-02-08 12:27

from django.db import migrations, models
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dmdb',
            fields=[
                ('id_obj', models.AutoField(primary_key=True, serialize=False)),
                ('tx_obj', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('timestamp_obj', models.DateTimeField(auto_now_add=True)),
                ('json_obj', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
